### PR TITLE
.NET Sonar Scanner

### PR DESCRIPTION
**Pull request by ianmburns**
# PR Details

Adds the ability to scan .NET solutions using the [.NET Sonar Scanner](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-msbuild/).

## Description

.NET Applications require a separate sonar scanner (linked above). The biggest differences between this and the original scanner is that the .NET scanner does not and can not use a properties file to define configuration (e.g. project-key). All configuration must be passed in via command line, and project-key is required.

Code coverage is reported by [Coverlet](https://github.com/coverlet-coverage/coverlet). Instructions and an example is provided in the documentation.

This step requires the [.NET image](https://github.com/boozallen/sdp-images/pull/33) be available as it has the required tools installed into the global .NET tools directory. The tools required are the sonar scanner, and the coverlet library.

## How Has This Been Tested

Unit tests for both the original sonar scanner and the dotnet sonar scanner have been written to ensure the underlying shell commands are executed correctly.

The dotnet scanner step has been tested as part of a Jenkins pipeline using the aforementioned dotnet image.

There was some light refactoring since the surrounding code to connect to Sonarqube and get the environment variables are the same between this and the original sonar scanner.

## Types of Changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I am submitting this pull request to the appropriate branch
- [x] I have labeled this pull request appropriately
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by psig-bah** [comment]
Working on reviewing library locally and will plan to convert docs to new mkdocs format before approving & merging.

**Comment by ConnorDY** [comment]
Any updates on this?

**Comment by ltdonner** [comment]
Hello - are there any updates on this PR?

**Comment by cokieffebah** [comment]
I think we needed to update or review the documents

**Pull request closed without merging**
