### PR TITLE
Adding the pull request comment library

### PR DESCRIPTION
**Pull request by darth-kermit**
# PR Details

This PR adds the ability to automatically comment on a GitHub enterprise pull request using JTE. 

## Description

Call this library in your Jenkinsfile and pass it a string to comment back to the PR in your pipeline. This step must be used within an on_pull_request block.

## How Has This Been Tested

**Testing TBD**

## Types of Changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I am submitting this pull request to the appropriate branch
- [ ] I have labeled this pull request appropriately
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by steven-terrana** [comment]
testing!

**Comment by steven-terrana** [comment]
I have many thoughts about this :)

## Usage? 

First, I like the concept of the SDP libraries being able to comment on Pull Requests. 

That being said, I have questions about how this is expected to be used.  Is the anticipated use case that this be done in the pipeline template or in the other pipeline libraries? 

In what scenarios do we expect to publish comments to the PR? 

## Should we take care of #74 first? 

it gives me pause to add more functionality to the github_enterprise library prior to completing #74 given this library is going to be deprecated along with `github` and `gitlab` in favor of a generic `git` library. 

## Implementation

To be consistent in how we're interacting with remote GitHub repositories, i'd suggest we continue leveraging the [hub4j/github-api](https://github.com/hub4j/github-api) we're using to get the source branch of a Pull Request as shown [here](https://github.com/boozallen/sdp-libraries/blob/master/libraries/github/github_enterprise.groovy#L15-L20)

something like: 
**GitHub**: 
```
GitHub.connectUsingOAuth(PAT)
  .getRepository("${env.ORG_NAME}/${env.REPO_NAME}")
  .getPullRequest(env.CHANGE_ID.toInteger())
  .comment("THE COMMENT")
```

**GitHub Enterprise**: 
```
GitHub.connectToEnterprise(ghUrl, PAT).getRepository("${env.ORG_NAME}/${env.REPO_NAME}")
  .getPullRequest(env.CHANGE_ID.toInteger())
  .comment("THE COMMENT") 
```

**Comment by cokieffebah** [comment]
reading @steven-terrana  comments, I think we should do issue #74 first, which will be resolved by PR #110.  Then we should rework the code as @steven-terrana  agrees with the concept.

**Comment by cokieffebah** [comment]
@darth-kermit could you answer the question about the use case ... whether the call is made from pipeline libraries or in pipeline templates?

**Comment by cokieffebah** [comment]
This PR would need to be re-written to match the current library struct. sorry about taking so long to review

**Pull request closed without merging**
