### PR TITLE
Openshift Library Updates

### PR DESCRIPTION
**Pull request by kottoson**
# PR Details

Image shas in the values file were moved under "global" to allow for subcharts; formatting (i.e. spelling-out) of numbers in Git Repo names; for each application environment, you can now specify a branch of the helm-configuration-repository to use; documentation updates

## Description

1. In the values file, the ``image_shas`` key is now stored under the ``global`` key in the values file. 
   * The ``global`` key is special in that it's available to all subcharts
   * Now a template doesn't need to be at the root level of the Helm chart to reference the image_shas

2. Numbers found in repository names are now spelled out. 
   * Like hyphens, they're allowed in repository names but not in YAML keys. 
   * Both cardinal (0,1, ..., 9) and ordinal (1st, 2nd, ..., 9th) are handled appropriately. 
   * Only single digit numbers are handled
      * this should cover most use cases
      * numbers with >1 digit will still be spelled out, but the resulting YAML keys may not read the same way
   * Examples:
      * _may-9-demo_ -> _may_nine_demo_
      * _my-2nd-project_ -> _my_second_project_

*EDIT*: Instead of what's above for (2)...
    1. images are stored in a key under `global`, called `repos`, whose value is a _list_ of _maps_
    2. each of the _maps_ in `repos` contains two keys: `name` and `sha`
    3. `name` records the app source code repository name
    4. `sha` keeps track of the latest git sha for that repository
    5. new entries are added to `repos` if you're deploying from a repository's pipeline for the first time

3. Users can now select a branch of the helm configuration repository when deploying to, or creating ephemeral environments for, a given application environment
   * The branch name is set using the `helm_chart_branch` config. option of the application_environment parameter of ``deploy_to`` and ``ephemeral``
   * The branch name defaults to "master", which is the current default

4. The unit tests and documentation updates
   * updates to cover new features
   * unit test updates
   * minor fixes for spelling, formatting errors

## How Has This Been Tested

1. Similar features were being successfully used in my previous project
2. I was able to deploy a sample application and helm chart to Openshift
3. Unit tests pass

## Types of Changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I am submitting this pull request to the appropriate branch
- [x] I have labeled this pull request appropriately
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by steven-terrana** [comment]
i don't think we should be improving the `formatRepoName` functionality. 

I think we should update the format of the data stored for shas from:
```
image_shas: 
  repo_1: <git sha> 
  repo_2: <git sha>
```

to: 
```
image_shas: 
- name: my-super-coolrepo1
   sha: <git sha> 
- name: my-other-repo2
   sha: <git sha
```

so that we don't have to do that hacky translation we're currently doing

**Comment by kottoson** [comment]
Sounds like a good idea! So you'd replace the section here:

https://github.com/boozallen/sdp-libraries/blob/24d0b1c7147a9faa7c4ddcbb5d38ef4c637f4b6b/libraries/openshift/deploy_to.groovy#L121-L123

with something like this:

```
def i = values.repos.findIndexOf { it.name == env.REPO_NAME } >= 0 ? values.repos.findIndexOf { it.name == name } : values.repos.size()
values.repos.[i] = [name: env.REPO_NAME, image_sha: newSHA]
```

**Comment by steven-terrana** [comment]
yeah! sounds right. 

readability tweak:

```
def repos = [[name: "repo-1", image_sha: "abcdef"], [name: "repo-2", image_sha: "123456"]]
println "before: ${repos}"
def env = [REPO_NAME: "repo-2"]
newSHA = "a1b2c3"
def name = env.REPO_NAME
def idx = repos.findIndexOf { it.name == name }

// repo doesn't exist yet
if(idx == -1){
    idx = repos.size()
}

repos[i] = [name: name, image_sha: newSHA]
println "after: ${repos}"
```

**Comment by kottoson** [comment]
@steven-terrana following up on our DMs, I've
* implemented the changes around the new values file format
* updated the unit tests
* tested the changes with a simple pipeline
* updated the docs

**Pull request merged**
