### PR TITLE
Adds support for build arguments to docker library

### PR DESCRIPTION
**Pull request by dstrivelli**
# PR Details
Adds function get_build_arg_string to docker library so that build arguments passed in through the pipeline configuration file are appended to the docker build command.

## Description
```
returns a string of build arguments that gets appended to 
  the `docker build` command in the build() function.

  There are two types or build arguments currently supported by this library,
  "credential" - will look in Jenkins for credentials of type "Secret Text" that are identified by "id"
  "inline" - value is not a secret and is defined directly in the configuration

  "Build Args" are passed to the library through the pipeline configuration like:

  docker{
    repo_path_prefix = env.PKG_REPO ?: "my-repo-path"
    build_args = [
      GITHUB_TOKEN : [type: "credential", id:"github_token"],
      SOME_VALUE : [type: "inline", value:"some-inline-value-here"]
    ]
  }
  
  get_build_arg_string()
  returns: "--build-arg GITHUB_TOKEN=some-credential-stored-in-jenkins --build-arg SOME_VALUE=some-inline-value-here"

```
## Types of Changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I am submitting this pull request to the appropriate branch
- [ ] I have labeled this pull request appropriately
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kottoson** [comment]
LGTM, just wanted to add some food for thought...
Are there any concerns around retrieving credentials and storing them in variables outside a `withCredentials` block (non-rhetorical question; I genuinely don't know)? Here's how I was fetching build args when I was tinkering, as a potential alternative. (For context, I was trying to build an image w/ sensitive info using Docker buildkit)

```
    def build_arg_creds = []
    def index = 0

    for (build_arg in config.buildkit.build_args){

      build_arg_creds << string(credentialsId: build_arg.id, variable: "cred${index}")
      build_cmd_args += "--build-arg $build_arg.name=\$cred${index} "
      index++
    }
    //build & push image
    withCredentials(build_arg_creds) {
      sh "DOCKER_BUILDKIT=1 docker build ${img.context} -t ${img.registry}/${img.repo}:${img.tag} " + build_cmd_args
      sh "docker push ${img.registry}/${img.repo}:${img.tag}"
    }
```

**Comment by dstrivelli** [comment]
> LGTM, just wanted to add some food for thought...
> Are there any concerns around retrieving credentials and storing them in variables outside a `withCredentials` block (non-rhetorical question; I genuinely don't know)? Here's how I was fetching build args when I was tinkering, as a potential alternative. (For context, I was trying to build an image w/ sensitive info using Docker buildkit)
> 
> ```
>     def build_arg_creds = []
>     def index = 0
> 
>     for (build_arg in config.buildkit.build_args){
> 
>       build_arg_creds << string(credentialsId: build_arg.id, variable: "cred${index}")
>       build_cmd_args += "--build-arg $build_arg.name=\$cred${index} "
>       index++
>     }
>     //build & push image
>     withCredentials(build_arg_creds) {
>       sh "DOCKER_BUILDKIT=1 docker build ${img.context} -t ${img.registry}/${img.repo}:${img.tag} " + build_cmd_args
>       sh "docker push ${img.registry}/${img.repo}:${img.tag}"
>     }
> ```

It's definitely a good question. @steven-terrana probably has some good insight here. Perhaps going from Jenkins Secret to Docker secret first and then launching the container with those secrets?

**Comment by steven-terrana** [comment]
https://github.com/dstrivelli/sdp-libraries/pull/1

My feedback was captured in this PR.

**Comment by dstrivelli** [comment]
I merged in @steven-terrana's feedback after reviewing and going over the changes with him on the phone. Thank you Steven for the education! You are the best!

**Pull request merged**
