### PR TITLE
[AIOPS-32] Small changes to avoid requiring an existing workspace whe…

### PR DESCRIPTION
**Pull request by kdendtler**
Small changes to avoid requiring an existing workspace when using git

# PR Details

Small changes to avoid requiring an existing workspace when using git

## Description

Configurable Init to avoid requiring an existing workspace when using git

## How Has This Been Tested

Tested locally and on AIOPS project from forked branch

## Types of Changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I am submitting this pull request to the appropriate branch
- [x] I have labeled this pull request appropriately
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kdendtler** [comment]
@steven-terrana Just double checking on this PR and the migration of the maven functionality into the main branch. If there's anything you need from me, please let me know.

**Comment by cokieffebah** [comment]
@kdendtler, this PR is outdated. Not your fault, we took too long to review.  Check this code and see if this PR is still valid. 
 I dont think it is.  If so, this PR should be changed to be against `main` not `master`.

**Comment by cokieffebah** [comment]
@kdendtler yeah just re-iterating the lateness on our part. My last comment was also asking you to check the newest version of git/git_distributions, https://github.com/boozallen/sdp-libraries/blob/main/libraries/git/steps/git_distributions.groovy, and see if that satisfies your intent for this PR. that git distributions has a try/catch around its `unstash`

**Comment by kdendtler** [comment]
@cokieffebah Sorry I totally missed this response. Those changes look like they will work fine so I'm good with closing this PR. Thanks again!

**Pull request closed without merging**
