### PR TITLE
Adding in Support for Maven and Docker Compose

### PR DESCRIPTION
**Pull request by kdendtler**
# PR Details

Adding in library support for Maven and Docker Compose. Minor change to allow using withGit without the workspace setup by passing in a configuration. 

## Description

Added library for Maven that supports phases, goals, profiles, and properties. Requires Maven installed on Jenkins.
Added library for Docker Compose that supports up and down commands with multiple files, environment variables, and the ability to pause the pipeline for some amount of time to ensure the containers have had time to deploy before continuing. 

## How Has This Been Tested
Tested on local Jenkins deployment using all parameters to build a Maven project, deploy containers, execute integration tests against those containers, and tear down when done. 
Automated tests written for both libraries and all existing and new tests pass.

## Types of Changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I am submitting this pull request to the appropriate branch
- [x] I have labeled this pull request appropriately
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by cokieffebah** [comment]
Sorry @kdendtler, just wrapper up a release.  going through library PR's now.  Thanks for the patience

**Comment by cokieffebah** [comment]
Could you break this PR into different PR's for each library? like a PR for the maven, a different PR for the git changes.  Some of them we would like to integrate and others we have questions about.   Thanks.

**Comment by kdendtler** [comment]
@cokieffebah I can do that if you prefer, but would it be easier to just address the comments about the PR here rather than creating 3 separate PRs?

**Comment by cokieffebah** [comment]
Commenting here might help with resubmitting but there will need to be multiple PRs.  This PR is for at least 3 different libraries. Docker Compose, Git, Maven   The ones that are tied together can be submitted together.  I realize it was probably easier to submit the current repo as a full changeset.  the 'git checkout', we would approve and be able to add quickly.  @steven-terrana has questions about either the Docker Compose or the Maven changes.  I think the config.withWorkspace would not be approved, I have to remember 'why' but recall I agree with its rejection.

**Comment by cokieffebah** [comment]
can you put the `git checkout` change against the `main` branch.  If this is an issue, I can move the code there but I would like for you to show up as the committer.  I realize that the library structure is different, now , in `main`

**Comment by kdendtler** [comment]
I've opened 4 PRs. I've moved the git checkout change to merge into the main branch. 
Let me know what questions you have on the other three PRs on each one. I believe the suggestion for the withWorkspace change was from this team, but I'm more than happy to adjust the strategy. 

I'll go ahead and close this PR in favor of the individual ones.

**Comment by cokieffebah** [comment]
Thanks.  I should have ask for the separate PRs but I forgot.  The `withWorkspace` issue I have to talk to @steven-terrana about 'a better solution'.  Thanks again

**Pull request closed without merging**
